package model.enums;

public enum ExceptionEnum {
    INVALID_LOGIN_EXCEPTION,
    FIN_NOT_FOUND_EXCEPTION,
    PERSIST_UNSUCCESSFULLY,
    DELETE_UNSUCCESSFULLY,
    UPDATE_UNSUCCESSFULLY,
    CREATE_UNSUCCESSFULLY,
    INVALID_OPTION, UNDER_AGE_EXCEPTION,
    INVALID_FIN_EXCEPTION,
    USER_ALREADY_EXIST_EXCEPTION,
    EMAIL_ALREADY_EXIST_EXCEPTION,
    BRAND_NO_FOUND_EXCEPTION,

}